### ISSUE TITLE
preview.vue文件中引用的css文件路径报错

### ISSUE THREAD

**Issue by haiyangJ** [LS1231/vue-preview#23]
引用方式
```
@import '~photoswipe/dist/photoswipe.css';
@import '~photoswipe/dist/default-skin/default-skin.css';
```

出错信息如下
```
Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.11, but postcss-partial-import uses 5.2.17. Perhaps this is the source of
 the error below.
Error: Failed to find '~photoswipe/dist/photoswipe.css'
    in [
        /Users/haiyang/Documents/workspace/rry/case-report-web/node_modules/vue-preview/src/plugins/preview
    ]
    at /Users/haiyang/Documents/workspace/rry/case-report-web/node_modules/postcss-import/lib/resolve-id.js:48:11
    at <anonymous>
 ERROR  Failed to compile with 1 errors                                                                                                 12:41:55

 error  in ./node_modules/vue-preview/src/plugins/preview/preview.vue

Module build failed: Error: Failed to find '~photoswipe/dist/photoswipe.css'
    in [
        /Users/haiyang/Documents/workspace/rry/case-report-web/node_modules/vue-preview/src/plugins/preview
    ]
    at /Users/haiyang/Documents/workspace/rry/case-report-web/node_modules/postcss-import/lib/resolve-id.js:48:11
    at <anonymous>

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?sourceMap!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-66e
7134e","scoped":false,"hasInlineConfig":false}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./node_modules/vue-preview/src/plug
ins/preview/preview.vue 4:14-277 13:3-17:5 14:22-285
 @ ./node_modules/vue-preview/src/plugins/preview/preview.vue
 @ ./node_modules/vue-preview/src/plugins/preview/index.js
 @ ./src/module/case/main.js
 @ multi ./build/dev-client ./src/module/case/main.js
```

是不是可以将两个css文件，放到js文件去请求呢?
我在...preview/index.js中请求正常
```
import PreviewComponent from './preview.vue'
import 'photoswipe/dist/photoswipe.css';
import 'photoswipe/dist/default-skin/default-skin.css';
```

**Comment by youngjuning** [comment]
同样的问题，找不到这俩组件

**Comment by wuweikd** [comment]
同样问题！！！！！！！！

**Comment by Mywifi** [comment]
+1

**Comment by xiaoshen110** [comment]
同样问题，求解决办法

**Comment by LS1231** [comment]
已修复
